name: Pull Request PlumDroid

on:
  pull_request:
    types: [ opened, closed, ready_for_review, reopened ]

jobs:
  # Add labels based on branch name
  add-branch-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add branch labels
        if: ${{ github.event.action == 'opened' }}
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pull-request-labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
